/* eslint-disable @typescript-eslint/no-explicit-any */
import { Chess } from 'chess.js';
import type { RepertoireNode } from '@/types/repertoire';

export const state: Record<string, any> = {
  chess: new Chess(),
  repertoires: [] as RepertoireNode[],
  activeRepIndex: -1,
  selectedSq: null,
  menuTarget: null,
  contextMenuMove: null,
  redoStack: [] as string[],
  boardFlipped: false,
  treeExpanded: new Set<string>(),
  repExpanded: new Set<string>(),
  selectedColor: 'w',
  contextMenuSource: '',
  varNameConflictConfirmed: false,
  freePlayRoot: null,
  currentNode: null,
  repFolders: {} as Record<string, string>,
  pendingNewRepFolderId: null,
  pendingNewRepFolderName: null,
  deleteTargetIdx: -1,
  pendingDeleteType: '',
  _suppressSync: false,
  trainingActive: false,
  trainingRoot: null,
  trainingRepColor: null,
  trainingMode: 'vertical',
  trainingLabel: '',
  trainingVisited: new Set<string>(),
  trainingIgnoredNoReply: new Set<string>(),
  trainingAnswered: new Set<string>(),
  trainingSkippedByError: new Set<string>(),
  trainingCompletedTargets: new Set<string>(),
  trainingExpectedChildId: null,
  trainingTotalTargets: 0,
  trainingSurvivalLives: 3,
  trainingSurvivalMaxLives: 3,
  trainingSurvivalGoldenHeart: false,
  trainingSurvivalMilestones: 0,
  trainingSurvivalMistakes: [] as any[],
  trainingLastSurvivalReport: null,
  trainingLastVictoryReport: null,
  trainingFeedback: null,
  boardTheme: { light: '#ebecd0', dark: '#779556' },
  pendingAnimation: null,
  skipNextAnimation: false,
  isAnalysisEnabled: false,
  analysisDepth: 10,
  analysisResults: [] as any[],
  analysisError: null,
  analysisSettings: { multiPV: 3, showArrows: true, arrowCount: 3 },
  moveAnnotations: {} as Record<string, any>,
  moveAnnotationScores: {} as Record<string, any>,
  moveAnnotationValues: {} as Record<string, any>,
  moveAnnotationPvs: {} as Record<string, any>,
  moveAnnotationsKey: '',
  moveAnnotationsVisibleKey: '',
  moveAnnotationsDepth: 0,
  moveAnnotationsCount: 0,
  moveAnnotationsLoading: false,
  moveAnnotationsComplete: false,
  auth: {
    mode: 'login',
    user: null,
    token: '',
    status: 'guest',
    error: '',
    isSubmitting: false,
    syncStatus: 'idle',
    syncMessage: '',
  },
  isGuestMode: false,
  userData: null,
  authMode: 'login',
  lichessStats: null,
  lastStatsRequestKey: '',
  statsCache: new Map<string, any>(),
  statsLoading: false,
  statsError: null,
  statsSelectedUci: '',
  statsShowAll: false,
  lichessProfile: null,
  medals: [],
  username: '',
  currentStatsRequestKey: '',
  pendingStatsRequest: null,
  statsEloMiniLoading: false,
  statsEloMiniLoaderUntil: 0,
  statsFilters: {
    eloPanelOpen: false,
    sortPanelOpen: false,
    eloMin: 0,
    eloMax: 3000,
    currentDatabase: 'lichess',
    sortBy: 'frequency',
    candidatesOpen: true,
    playerUsername: '',
    playerColor: 'white',
    playerTimeClass: 'all',
    playerDateFrom: '',
    playerDateTo: '',
    playerEloMin: 0,
    playerEloMax: 3000,
  },
  dynamicModals: null,
};

export function initState() {
  state.freePlayRoot = {
    id: 'free',
    fen: state.chess.fen(),
    children: [],
    parent: null,
    moveNum: 0,
    turn: 'b',
    san: 'Initial',
  };
  state.currentNode = state.freePlayRoot;
}
